name: Tests and Deploy

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm test

  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate App Token
        id: generate-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
          installation_id: ${{ secrets.APP_INSTALLATION_ID }}

      - name: Install @octokit/rest module
        run: npm install @octokit/rest

      - name: Trigger Deploy in Parent Repo
        uses: actions/github-script@v7
        with:
          script: |
            const { Octokit } = await import('@octokit/rest');
            const octokit = new Octokit({ 
              auth: `${{ steps.generate-token.outputs.token }}` 
            });
            await octokit.repos.createDispatchEvent({
              owner: 'chaparron',
              repo: 'timeTrackr',
              event_type: 'trigger-deploy'
            });